### ISSUE TITLE
Unable to start due to MongoDB

### ISSUE THREAD

**Issue by ThatAlbaPerson** [tuba8890/AccountGen#7]
Whenever I attempt to run `Start.py` i get the error:
`  File "/home/container/Start.py", line 42, in <module>
    mongo = PyMongo(app)
            ^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/flask_pymongo/__init__.py", line 110, in __init__
    self.init_app(app, uri, *args, **kwargs)
  File "/home/container/.local/lib/python3.11/site-packages/flask_pymongo/__init__.py", line 147, in init_app
    parsed_uri = uri_parser.parse_uri(uri)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/uri_parser.py", line 532, in parse_uri
    user, passwd = parse_userinfo(userinfo)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/uri_parser.py", line 88, in parse_userinfo
    raise InvalidURI(
pymongo.errors.InvalidURI: Username and password must be escaped according to RFC 3986, use urllib.parse.quote_plus`

my **MONGO_URI** is `mongodb+srv://example:examplepw@cluster0.example.mongodb.net/?retryWrites=true&w=majority`

**Comment by Marsi591** [comment]
Remove everything after ? From your string

**Comment by Marsi591** [comment]
Remove the qoutes it needs to be like this user:pass

**Comment by ThatAlbaPerson** [comment]
> Remove the qoutes it needs to be like this user:pass

In the `MONGO_URI` string?

**Comment by Marsi591** [comment]
Yes

**Comment by ThatAlbaPerson** [comment]
> Yes

I don't see any quotes?
`mongodb+srv://example:examplepw@cluster0.example.mongodb.net/?`

**Comment by Marsi591** [comment]
Weird

**Comment by Marsi591** [comment]
Normally it should work

**Comment by ThatAlbaPerson** [comment]
`  File "/home/container/Start.py", line 42, in <module>
    mongo = PyMongo(app)
            ^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/flask_pymongo/__init__.py", line 110, in __init__
    self.init_app(app, uri, *args, **kwargs)
  File "/home/container/.local/lib/python3.11/site-packages/flask_pymongo/__init__.py", line 147, in init_app
    parsed_uri = uri_parser.parse_uri(uri)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/uri_parser.py", line 470, in parse_uri
    user, passwd = parse_userinfo(userinfo)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/uri_parser.py", line 60, in parse_userinfo
    raise InvalidURI("Username and password must be escaped according to "
pymongo.errors.InvalidURI: Username and password must be escaped according to RFC 3986, use urllib.parse.quote_plus().`

**Comment by ThatAlbaPerson** [comment]
I managed to fix the error (It was because the password had an `@` in it) But now it is coming up with this whenever I attempt to reach the site:
`ERROR:Start:Exception on / [GET]
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/Start.py", line 76, in index
    siteSettings = mongo.db.site.find_one({"_id": "1"})
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/collection.py", line 1319, in find_one
    for result in cursor.limit(-1):
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/cursor.py", line 1207, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/cursor.py", line 1124, in _refresh
    self.__send_message(q)
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/cursor.py", line 999, in __send_message
    response = client._run_operation_with_response(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1368, in _run_operation_with_response
    return self._retryable_read(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
    with self._slaveok_for_server(read_pref, server, session,
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1309, in _slaveok_for_server
    with self._get_socket(server, session, exhaust=exhaust) as sock_info:
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1246, in _get_socket
    with server.get_socket(
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/pool.py", line 1225, in get_socket
    sock_info = self._get_socket(all_credentials)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/pool.py", line 1279, in _get_socket
    sock_info.check_auth(all_credentials)
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/pool.py", line 793, in check_auth
    self.authenticate(credentials)
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/pool.py", line 810, in authenticate
    auth.authenticate(credentials, self)
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/auth.py", line 673, in authenticate
    auth_func(credentials, sock_info)
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/auth.py", line 591, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/auth.py", line 295, in _authenticate_scram
    res = sock_info.command(source, cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/pool.py", line 683, in command
    return command(self, dbname, spec, slave_ok,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/network.py", line 159, in command
    helpers._check_command_response(
  File "/home/container/.local/lib/python3.11/site-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response,
pymongo.errors.OperationFailure: bad auth : Authentication failed., full error: {'ok': 0, 'errmsg': 'bad auth : Authentication failed.', 'code': 8000, 'codeName': 'AtlasError'}`

**Comment by ThatAlbaPerson** [comment]
Fixed it.
